/*
	Case Project
	Levi Farlee
	SDEV 250
	
	This code is used for the generation of a Google Maps display with the user's current location.
	The map is generated by the click event on a button.
*/

//strict mode
"use strict";

//global variables
var timerFail;

//page setup function
function setUpPage() {
	var mapButton = document.getElementById("mapBtn");
	mapButton.addEventListener("click", loadMap, false);
}

//function to load in Google Maps
function loadMap() {
	//if the map is already present, don't download again
	if (typeof google !== 'object') {
	   var script = document.createElement("script");
	   script.src = "https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true&callback=displayMap";
	   document.body.appendChild(script);
   }
}

//if user agrees, display their geolocation on map
function displayMap() {
	//timer via setTimeout to see if user selects an option within fifteen seconds
	timerFail = setTimeout(mapFail, 15000);
	
	//if geolocation is accessible / user agrees, then get current position
	if (navigator.geolocation) {
		navigator.geolocation.getCurrentPosition(getUserPosition, mapFail, {timeout: 10000});
	} else { //if user doesn't agree, call the mapFail() function.
		mapFail();
	}
}

//function to get user's position and display via Google Maps
function getUserPosition(position) {
	//reset failure timer (because user chose to share location)
	clearTimeout(timerFail);
	
	//create three variables to hold the user's lng, lat, and alt
	var currPosLng = position.coords.longitude;
	var currPosLat = position.coords.latitude;
	var currPosAlt = position.coords.altitude;
	if (currPosAlt === null) {
		currPosAlt = "Altitude could not be determined.";
	}
	
	//specify the map's settings before creation
	var mapSettings = {
		//set the map on the user's current location
		center: new google.maps.LatLng(currPosLat,currPosLng), zoom: 12
	};
	
	//create the map and place within the document
	var geoMap = new google.maps.Map(document.getElementById("geoMap"), mapSettings);
	document.querySelector("#geoMap").style.display = "block";
	
	//set mapSuccess p element to display user's lng/lat/alt
	document.getElementById("mapStatus").innerHTML = "Longitude: " + currPosLng + "<br>Latitude: " + currPosLat + "<br>Altitude: " + currPosAlt;
}

//function to handle failure to geolocate
function mapFail() {
	document.getElementById("mapStatus").innerHTML = "Unable to access your current location. Good choice!";
}

//add event listener to setup page on page load
window.addEventListener("load", setUpPage, false);